# Generated by Django 3.0.2 on 2020-01-21 02:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('answers', models.CharField(default='', max_length=500)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('c1', models.CharField(max_length=400)),
                ('c2', models.CharField(max_length=400)),
                ('c3', models.CharField(max_length=400)),
                ('c4', models.CharField(max_length=400)),
                ('correct_choice_id', models.IntegerField(default=1, validators=[django.core.validators.RegexValidator(message='You should Choice number between 1 to 4 only', regex='^[1-4]$')])),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizservice.Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizservice.Questions')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='quizservice.ExamQuestion', to='quizservice.Questions'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
