# Generated by Django 3.0.2 on 2020-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
